/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAutotradeRouteImport } from './routes/api/public/autotrade'
import { Route as ApiPublicScorecardRouteImport } from './routes/api/public/scorecard'
import { Route as ApiPublicSettleRouteImport } from './routes/api/public/settle'
import { Route as ApiPublicTradesRouteImport } from './routes/api/public/trades'
import { Route as ApiPublicCouncilBankRouteImport } from './routes/api/public/council/bank'
import { Route as ApiPublicCouncilExecuteRouteImport } from './routes/api/public/council/execute'
import { Route as ApiPublicCouncilProposeRouteImport } from './routes/api/public/council/propose'
import { Route as ApiPublicCouncilVoteRouteImport } from './routes/api/public/council/vote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutotradeRoute = ApiPublicAutotradeRouteImport.update({
  id: '/api/public/autotrade',
  path: '/api/public/autotrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScorecardRoute = ApiPublicScorecardRouteImport.update({
  id: '/api/public/scorecard',
  path: '/api/public/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSettleRoute = ApiPublicSettleRouteImport.update({
  id: '/api/public/settle',
  path: '/api/public/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTradesRoute = ApiPublicTradesRouteImport.update({
  id: '/api/public/trades',
  path: '/api/public/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCouncilBankRoute = ApiPublicCouncilBankRouteImport.update({
  id: '/api/public/council/bank',
  path: '/api/public/council/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCouncilExecuteRoute = ApiPublicCouncilExecuteRouteImport.update({
  id: '/api/public/council/execute',
  path: '/api/public/council/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCouncilProposeRoute = ApiPublicCouncilProposeRouteImport.update({
  id: '/api/public/council/propose',
  path: '/api/public/council/propose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCouncilVoteRoute = ApiPublicCouncilVoteRouteImport.update({
  id: '/api/public/council/vote',
  path: '/api/public/council/vote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/autotrade': typeof ApiPublicAutotradeRoute
  '/api/public/scorecard': typeof ApiPublicScorecardRoute
  '/api/public/settle': typeof ApiPublicSettleRoute
  '/api/public/trades': typeof ApiPublicTradesRoute
  '/api/public/council/bank': typeof ApiPublicCouncilBankRoute
  '/api/public/council/execute': typeof ApiPublicCouncilExecuteRoute
  '/api/public/council/propose': typeof ApiPublicCouncilProposeRoute
  '/api/public/council/vote': typeof ApiPublicCouncilVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/autotrade': typeof ApiPublicAutotradeRoute
  '/api/public/scorecard': typeof ApiPublicScorecardRoute
  '/api/public/settle': typeof ApiPublicSettleRoute
  '/api/public/trades': typeof ApiPublicTradesRoute
  '/api/public/council/bank': typeof ApiPublicCouncilBankRoute
  '/api/public/council/execute': typeof ApiPublicCouncilExecuteRoute
  '/api/public/council/propose': typeof ApiPublicCouncilProposeRoute
  '/api/public/council/vote': typeof ApiPublicCouncilVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/autotrade': typeof ApiPublicAutotradeRoute
  '/api/public/scorecard': typeof ApiPublicScorecardRoute
  '/api/public/settle': typeof ApiPublicSettleRoute
  '/api/public/trades': typeof ApiPublicTradesRoute
  '/api/public/council/bank': typeof ApiPublicCouncilBankRoute
  '/api/public/council/execute': typeof ApiPublicCouncilExecuteRoute
  '/api/public/council/propose': typeof ApiPublicCouncilProposeRoute
  '/api/public/council/vote': typeof ApiPublicCouncilVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/autotrade'
    | '/api/public/scorecard'
    | '/api/public/settle'
    | '/api/public/trades'
    | '/api/public/council/bank'
    | '/api/public/council/execute'
    | '/api/public/council/propose'
    | '/api/public/council/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/autotrade'
    | '/api/public/scorecard'
    | '/api/public/settle'
    | '/api/public/trades'
    | '/api/public/council/bank'
    | '/api/public/council/execute'
    | '/api/public/council/propose'
    | '/api/public/council/vote'
  id:
    | '__root__'
    | '/'
    | '/api/public/autotrade'
    | '/api/public/scorecard'
    | '/api/public/settle'
    | '/api/public/trades'
    | '/api/public/council/bank'
    | '/api/public/council/execute'
    | '/api/public/council/propose'
    | '/api/public/council/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAutotradeRoute: typeof ApiPublicAutotradeRoute
  ApiPublicScorecardRoute: typeof ApiPublicScorecardRoute
  ApiPublicSettleRoute: typeof ApiPublicSettleRoute
  ApiPublicTradesRoute: typeof ApiPublicTradesRoute
  ApiPublicCouncilBankRoute: typeof ApiPublicCouncilBankRoute
  ApiPublicCouncilExecuteRoute: typeof ApiPublicCouncilExecuteRoute
  ApiPublicCouncilProposeRoute: typeof ApiPublicCouncilProposeRoute
  ApiPublicCouncilVoteRoute: typeof ApiPublicCouncilVoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autotrade': {
      id: '/api/public/autotrade'
      path: '/api/public/autotrade'
      fullPath: '/api/public/autotrade'
      preLoaderRoute: typeof ApiPublicAutotradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scorecard': {
      id: '/api/public/scorecard'
      path: '/api/public/scorecard'
      fullPath: '/api/public/scorecard'
      preLoaderRoute: typeof ApiPublicScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/settle': {
      id: '/api/public/settle'
      path: '/api/public/settle'
      fullPath: '/api/public/settle'
      preLoaderRoute: typeof ApiPublicSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trades': {
      id: '/api/public/trades'
      path: '/api/public/trades'
      fullPath: '/api/public/trades'
      preLoaderRoute: typeof ApiPublicTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/council/bank': {
      id: '/api/public/council/bank'
      path: '/api/public/council/bank'
      fullPath: '/api/public/council/bank'
      preLoaderRoute: typeof ApiPublicCouncilBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/council/execute': {
      id: '/api/public/council/execute'
      path: '/api/public/council/execute'
      fullPath: '/api/public/council/execute'
      preLoaderRoute: typeof ApiPublicCouncilExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/council/propose': {
      id: '/api/public/council/propose'
      path: '/api/public/council/propose'
      fullPath: '/api/public/council/propose'
      preLoaderRoute: typeof ApiPublicCouncilProposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/council/vote': {
      id: '/api/public/council/vote'
      path: '/api/public/council/vote'
      fullPath: '/api/public/council/vote'
      preLoaderRoute: typeof ApiPublicCouncilVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAutotradeRoute: ApiPublicAutotradeRoute,
  ApiPublicScorecardRoute: ApiPublicScorecardRoute,
  ApiPublicSettleRoute: ApiPublicSettleRoute,
  ApiPublicTradesRoute: ApiPublicTradesRoute,
  ApiPublicCouncilBankRoute: ApiPublicCouncilBankRoute,
  ApiPublicCouncilExecuteRoute: ApiPublicCouncilExecuteRoute,
  ApiPublicCouncilProposeRoute: ApiPublicCouncilProposeRoute,
  ApiPublicCouncilVoteRoute: ApiPublicCouncilVoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
