/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAutotradeRouteImport } from './routes/api/public/autotrade'
import { Route as ApiPublicSettleRouteImport } from './routes/api/public/settle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutotradeRoute = ApiPublicAutotradeRouteImport.update({
  id: '/api/public/autotrade',
  path: '/api/public/autotrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSettleRoute = ApiPublicSettleRouteImport.update({
  id: '/api/public/settle',
  path: '/api/public/settle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/autotrade': typeof ApiPublicAutotradeRoute
  '/api/public/settle': typeof ApiPublicSettleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/autotrade': typeof ApiPublicAutotradeRoute
  '/api/public/settle': typeof ApiPublicSettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/autotrade': typeof ApiPublicAutotradeRoute
  '/api/public/settle': typeof ApiPublicSettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/autotrade' | '/api/public/settle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/autotrade' | '/api/public/settle'
  id: '__root__' | '/' | '/api/public/autotrade' | '/api/public/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAutotradeRoute: typeof ApiPublicAutotradeRoute
  ApiPublicSettleRoute: typeof ApiPublicSettleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autotrade': {
      id: '/api/public/autotrade'
      path: '/api/public/autotrade'
      fullPath: '/api/public/autotrade'
      preLoaderRoute: typeof ApiPublicAutotradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/settle': {
      id: '/api/public/settle'
      path: '/api/public/settle'
      fullPath: '/api/public/settle'
      preLoaderRoute: typeof ApiPublicSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAutotradeRoute: ApiPublicAutotradeRoute,
  ApiPublicSettleRoute: ApiPublicSettleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
